name: Publish a snapshot release

on:
  push:
    branches:
      - master

jobs:
  publish_snapshot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - uses: actions/setup-java@a18c333f3f14249953dab3e186e5e21bf3390f1d
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Setup Gradle
        uses: gradle/gradle-build-action@6095a76664413da4c8c134ee32e8a8ae900f0f1f
        with:
          gradle-version: wrapper

      - name: Publish the artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
        run: ./gradlew publish
